cargo-features = ["edition2024"]

[package]
name = "mosaic-snitch"
version = "0.1.0"
edition = "2024"

[dependencies]
mosaic-model = "0.1.1"
tokio = { version = "1.44.1",  features = ["full"] }
url = "2.5.4"
